name: "Action Setup SSH"

description: "A GitHub Action to configure SSH keys and host fingerprints"

inputs:
  name:
    description: "The name of the SSH identity such as: id_ed25519."
    type: string
    default: id_ed25519
    required: false
  public_key:
    description: "The Public Key for your runner's ssh identity."
    type: string
    required: false
  private_key:
    description: "The Private Key for your runner's ssh identity."
    type: string
    required: false
  host:
    description: "The host to scan and add fingerprints for in known_hosts."
    type: string
    required: false
  port:
    description: "The port on the host to scan."
    type: string
    default: 22
    required: false

runs:
  using: "composite"
  steps:
    - name: Create .ssh Directory
      shell: bash
      run: mkdir -p ~/.ssh

    - name: Save Public Key
      shell: bash
      if: "${{ inputs.public_key != '' }}"
      run: |
        echo "${{ inputs.public_key }}" > ~/.ssh/${{ inputs.name }}.pub
        chmod 600 ~/.ssh/${{ inputs.name }}.pub

    - name: Save Private Key
      shell: bash
      if: "${{ inputs.private_key != '' }}"
      run: |
        echo "${{ inputs.private_key }}" > ~/.ssh/${{ inputs.name }}
        chmod 600 ~/.ssh/${{ inputs.name }}

    - name: Setup known_hosts File
      shell: bash
      if: "${{ inputs.host != '' }}"
      run: ssh-keyscan -p ${{ inputs.port }} ${{ inputs.host }} >> ~/.ssh/known_hosts
